# Stage 1: Build the application with Maven
FROM maven:3.8.4-openjdk-8 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

# Stage 2: Copy the built application to a new container
FROM openjdk:8-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar ./app.jar
EXPOSE 8080 5005
ENTRYPOINT ["java", "-jar", "app.jar"]
