version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    restart: no

  db:
    image: postgres:14-alpine
    container_name: db
    restart: no
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: dothelist_db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
